### ISSUE TITLE
Registry responded to head request with "404 Not Found" for single image

### ISSUE THREAD

**Issue by fkrauthan** [containrrr/watchtower#1540] opened 2023-01-28 03:07 UTC
### Describe the bug

For some reason one image from docker hub [weblate/weblate](https://hub.docker.com/r/weblate/weblate) keeps triggering the error email:

```
Could not do a head request for "weblate/weblate:latest", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"
```

no other image on my instance is getting this error and the image seem to be present on docker hub. So not sure if its some issue with their APIs or a bug that sometimes gets triggered within Watchtower in checking for image updates.

Based on the logs it seems to happen intermittently. 

### Steps to reproduce

1. Run image `weblate/weblate:latest`
2. Run watchtower to update weblate
3. Check logs or wait for error email

### Expected behavior

The image gets checked for updates without issues

### Environment

- Platform: Ubuntu (Linux)
- Architecture: x86_64
- Docker Version: 20.10.23

### Your logs

```text
time="2023-01-28T00:36:07Z" level=info msg="Session done" Failed=0 Scanned=38 Updated=0 notify=no
time="2023-01-28T00:51:06Z" level=info msg="Session done" Failed=0 Scanned=38 Updated=0 notify=no
time="2023-01-28T01:06:06Z" level=info msg="Session done" Failed=0 Scanned=38 Updated=0 notify=no
time="2023-01-28T01:20:20Z" level=warning msg="Could not do a head request for \"weblate/weblate:latest\", falling back to regular pull." container=/weblate-server image="weblate/weblate:latest"
time="2023-01-28T01:20:20Z" level=warning msg="Reason: registry responded to head request with \"404 Not Found\", auth: \"not present\"" container=/weblate-server image="weblate/weblate:latest"
time="2023-01-28T01:21:08Z" level=info msg="Session done" Failed=0 Scanned=39 Updated=0 notify=no
time="2023-01-28T01:36:06Z" level=info msg="Session done" Failed=0 Scanned=38 Updated=0 notify=no
time="2023-01-28T01:51:07Z" level=info msg="Session done" Failed=0 Scanned=38 Updated=0 notify=no
time="2023-01-28T02:06:06Z" level=info msg="Session done" Failed=0 Scanned=38 Updated=0 notify=no
time="2023-01-28T02:21:07Z" level=info msg="Session done" Failed=0 Scanned=38 Updated=0 notify=no
time="2023-01-28T02:35:19Z" level=warning msg="Could not do a head request for \"weblate/weblate:latest\", falling back to regular pull." container=/weblate-server image="weblate/weblate:latest"
time="2023-01-28T02:35:19Z" level=warning msg="Reason: registry responded to head request with \"404 Not Found\", auth: \"not present\"" container=/weblate-server image="weblate/weblate:latest"
time="2023-01-28T02:36:08Z" level=info msg="Session done" Failed=0 Scanned=39 Updated=0 notify=no
time="2023-01-28T02:51:07Z" level=info msg="Session done" Failed=0 Scanned=38 Updated=0 notify=no
time="2023-01-28T03:06:06Z" level=info msg="Session done" Failed=0 Scanned=38 Updated=0 notify=no
```

**Comment by kimpenhaus** [comment] 2023-01-28 13:55
I guess it is the same reason as for #1528

**Comment by piksel** [comment] 2023-01-29 10:38
Closed as duplicate of sticky issue #1528 (with workaround in discussion #1529)

**Closed as completed** 2023-01-29 10:38 UTC
Labels: Status: Duplicate

**Comment by fkrauthan** [comment] 2023-01-29 18:51
@piksel but the linked issue is already closed while the issue is still active? Does that mean a new watchtower update suppose to be coming soon?

**Comment by piksel** [comment] 2023-01-29 20:40
A new version has been released. The issues close when code that fixes them is merged.
