### ISSUE TITLE
Default "update all" parameter

### ISSUE THREAD

**Issue by redge76** [containrrr/watchtower#167] opened 2018-02-23 12:20 UTC
Am I the only one to dislike the default behavior which is to update all running containers ?
Don't you think a "do noting" would be better ?
Then a new parameter "--all" would trigger the same behavior as today ?

I need to update only a subset of my containers and I use the "--label-enable". 
For me, the "update all" default is dangerous....

**Comment by stffabi** [comment] 2018-02-27 16:40
Thanks for your report. I completely understand your feeling about the current behaviour. The problem is changing a behaviour like this on a widely deployed software is always a problem and breaks things out there. Unfortunately a lot of people use just the `latest` tag of the container and not a specific minor, therefore all of those people will end up by a watchtower instance that doesn't do anything. The self-updating nature of watchtower makes this quite more annoying. Well we could just print out an error and stop executing watchtower, but also that wouldn't be a good user experience for those people.

**Comment by redge76** [comment] 2018-02-28 22:28
I understand your point. Now it's hard to revert to a safe behaviour.
To me it feels like having the "rm" command deleting all the files  on your system by default and you have to specify which files you want to keep each time you type it.... It's just disaster waiting to happen...
watchtower is dangerous on real production environment.
We need a fork to watchtower_safe :-(

**Comment by stffabi** [comment] 2018-03-03 21:28
A safer behaviour has been implemented, as discussed in #169. Hopefully we could one day improve the interface...

**Comment by stffabi** [comment] 2018-03-03 21:33
I'll close the issue for the time being and start a discussion in the near future how we could proceed with such interface changes. Thanks again @redge76 for bringing this up.

**Closed as completed by stffabi** 2018-03-03 21:33 UTC
